/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EditPropertyRouteImport } from './routes/edit-property'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LandlordRouteImport } from './routes/landlord'
import { Route as LandlordProfileRouteImport } from './routes/landlord-profile'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PropertyIdRouteImport } from './routes/property.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EditPropertyRoute = EditPropertyRouteImport.update({
  id: '/edit-property',
  path: '/edit-property',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordProfileRoute = LandlordProfileRouteImport.update({
  id: '/landlord-profile',
  path: '/landlord-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/edit-property': typeof EditPropertyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/landlord': typeof LandlordRoute
  '/landlord-profile': typeof LandlordProfileRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/edit-property': typeof EditPropertyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/landlord': typeof LandlordRoute
  '/landlord-profile': typeof LandlordProfileRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/dashboard': typeof DashboardRoute
  '/edit-property': typeof EditPropertyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/landlord': typeof LandlordRoute
  '/landlord-profile': typeof LandlordProfileRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/edit-property'
    | '/how-it-works'
    | '/landlord'
    | '/landlord-profile'
    | '/list-property'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/signup'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/edit-property'
    | '/how-it-works'
    | '/landlord'
    | '/landlord-profile'
    | '/list-property'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/signup'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/edit-property'
    | '/how-it-works'
    | '/landlord'
    | '/landlord-profile'
    | '/list-property'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/signup'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  DashboardRoute: typeof DashboardRoute
  EditPropertyRoute: typeof EditPropertyRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LandlordRoute: typeof LandlordRoute
  LandlordProfileRoute: typeof LandlordProfileRoute
  ListPropertyRoute: typeof ListPropertyRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-property': {
      id: '/edit-property'
      path: '/edit-property'
      fullPath: '/edit-property'
      preLoaderRoute: typeof EditPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord': {
      id: '/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord-profile': {
      id: '/landlord-profile'
      path: '/landlord-profile'
      fullPath: '/landlord-profile'
      preLoaderRoute: typeof LandlordProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  DashboardRoute: DashboardRoute,
  EditPropertyRoute: EditPropertyRoute,
  HowItWorksRoute: HowItWorksRoute,
  LandlordRoute: LandlordRoute,
  LandlordProfileRoute: LandlordProfileRoute,
  ListPropertyRoute: ListPropertyRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
