
-- Room Renter: saved rooms, messaging, notifications, reviews and landlord verification
-- Run this in Supabase SQL Editor once.

alter table public.profiles
  add column if not exists phone text,
  add column if not exists permanent_address text,
  add column if not exists aadhaar_last4 text,
  add column if not exists aadhaar_verified boolean not null default false;

alter table public.properties
  add column if not exists landlord_name text,
  add column if not exists landlord_phone text,
  add column if not exists landlord_identity_verified boolean not null default false;


-- Landlords can manage their own verification fields.
alter table public.profiles enable row level security;
drop policy if exists "profiles own select" on public.profiles;
create policy "profiles own select" on public.profiles
for select using (id = auth.uid());

drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles
for update using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "profiles own insert" on public.profiles;
create policy "profiles own insert" on public.profiles
for insert with check (id = auth.uid());

create table if not exists public.saved_properties (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id bigint not null references public.properties(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, property_id)
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete set null,
  renter_id uuid not null references auth.users(id) on delete cascade,
  landlord_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(property_id, renter_id, landlord_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(trim(body)) between 1 and 5000),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text,
  type text not null default 'general',
  reference_id bigint,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.property_reviews (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  reviewer_id uuid not null references auth.users(id) on delete cascade,
  reviewer_name text not null default 'Verified Renter',
  rating integer not null check (rating between 1 and 5),
  review text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(property_id, reviewer_id)
);

alter table public.property_reviews
  add column if not exists reviewer_name text not null default 'Verified Renter';

-- Keep the existing rating/reviews columns on properties in sync with real reviews.
create or replace function public.refresh_property_rating()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_property_id bigint;
begin
  target_property_id := coalesce(new.property_id, old.property_id);

  update public.properties
  set
    rating = coalesce(
      (select round(avg(rating)::numeric, 1)
       from public.property_reviews
       where property_id = target_property_id),
      0
    ),
    reviews = (
      select count(*)
      from public.property_reviews
      where property_id = target_property_id
    )
  where id = target_property_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists property_reviews_rating_trigger on public.property_reviews;
create trigger property_reviews_rating_trigger
after insert or update or delete on public.property_reviews
for each row execute function public.refresh_property_rating();

-- Automatically notify a landlord when a new review is posted.
create or replace function public.notify_landlord_new_review()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_id uuid;
begin
  select landlord_id into owner_id from public.properties where id = new.property_id;
  if owner_id is not null and owner_id <> new.reviewer_id then
    insert into public.notifications(user_id, title, body, type, reference_id)
    values (
      owner_id,
      'New property review',
      'A renter left a ' || new.rating || '-star review on your property.',
      'review',
      new.property_id
    );
  end if;
  return new;
end;
$$;

drop trigger if exists property_review_notification_trigger on public.property_reviews;
create trigger property_review_notification_trigger
after insert on public.property_reviews
for each row execute function public.notify_landlord_new_review();

-- Automatically notify a recipient when a message is sent.
create or replace function public.notify_new_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient_id uuid;
begin
  select
    case
      when renter_id = new.sender_id then landlord_id
      else renter_id
    end
  into recipient_id
  from public.conversations
  where id = new.conversation_id;

  if recipient_id is not null then
    insert into public.notifications(user_id, title, body, type, reference_id)
    values (
      recipient_id,
      'New message',
      left(new.body, 160),
      'message',
      new.conversation_id
    );
  end if;
  return new;
end;
$$;

drop trigger if exists messages_notification_trigger on public.messages;
create trigger messages_notification_trigger
after insert on public.messages
for each row execute function public.notify_new_message();

-- Updated timestamp helpers.
create or replace function public.touch_conversation()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists conversations_updated_at_trigger on public.conversations;
create trigger conversations_updated_at_trigger
before update on public.conversations
for each row execute function public.touch_conversation();

-- RLS
alter table public.saved_properties enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.property_reviews enable row level security;

drop policy if exists "saved own select" on public.saved_properties;
create policy "saved own select" on public.saved_properties for select using (user_id = auth.uid());
drop policy if exists "saved own insert" on public.saved_properties;
create policy "saved own insert" on public.saved_properties for insert with check (user_id = auth.uid());
drop policy if exists "saved own delete" on public.saved_properties;
create policy "saved own delete" on public.saved_properties for delete using (user_id = auth.uid());

drop policy if exists "conversation participant select" on public.conversations;
create policy "conversation participant select" on public.conversations
for select using (renter_id = auth.uid() or landlord_id = auth.uid());
drop policy if exists "conversation participant insert" on public.conversations;
create policy "conversation participant insert" on public.conversations
for insert with check (renter_id = auth.uid() or landlord_id = auth.uid());
drop policy if exists "conversation participant update" on public.conversations;
create policy "conversation participant update" on public.conversations
for update using (renter_id = auth.uid() or landlord_id = auth.uid());

drop policy if exists "message participant select" on public.messages;
create policy "message participant select" on public.messages
for select using (
  exists (
    select 1 from public.conversations c
    where c.id = conversation_id
      and (c.renter_id = auth.uid() or c.landlord_id = auth.uid())
  )
);
drop policy if exists "message sender insert" on public.messages;
create policy "message sender insert" on public.messages
for insert with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.conversations c
    where c.id = conversation_id
      and (c.renter_id = auth.uid() or c.landlord_id = auth.uid())
  )
);
drop policy if exists "message participant update" on public.messages;
create policy "message participant update" on public.messages
for update using (
  exists (
    select 1 from public.conversations c
    where c.id = conversation_id
      and (c.renter_id = auth.uid() or c.landlord_id = auth.uid())
  )
);

drop policy if exists "notifications own select" on public.notifications;
create policy "notifications own select" on public.notifications for select using (user_id = auth.uid());
drop policy if exists "notifications own update" on public.notifications;
create policy "notifications own update" on public.notifications for update using (user_id = auth.uid());

drop policy if exists "reviews public select" on public.property_reviews;
create policy "reviews public select" on public.property_reviews for select using (true);
drop policy if exists "reviews own insert" on public.property_reviews;
create policy "reviews own insert" on public.property_reviews
for insert with check (reviewer_id = auth.uid());
drop policy if exists "reviews own update" on public.property_reviews;
create policy "reviews own update" on public.property_reviews
for update using (reviewer_id = auth.uid()) with check (reviewer_id = auth.uid());
drop policy if exists "reviews own delete" on public.property_reviews;
create policy "reviews own delete" on public.property_reviews
for delete using (reviewer_id = auth.uid());

